(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-PDF-mode t)
 '(TeX-auto-save t)
 '(TeX-byte-compile t)
 '(TeX-clean-confirm nil)
 '(TeX-master (quote dwim))
 '(TeX-parse-self t)
 '(TeX-source-correlate-mode t)
 '(TeX-view-program-selection (quote ((output-pdf "Evince") (output-html "xdg-open"))))
 '(abbrev-file-name "/home/michael/.emacs.d/.abbrev_defs")
 '(aggressive-indent-comments-too nil)
 '(auto-revert-verbose nil)
 '(custom-safe-themes
   (quote
    ("efefb69e7781fcfe62f3d0b573701f56e45e29afbe9e378a422025fd767ea246" default)))
 '(dashboard-startup-banner (quote logo) t)
 '(flycheck-display-errors-delay 0.3)
 '(flycheck-pylintrc "~/.pylintrc")
 '(flycheck-python-pylint-executable "/usr/bin/pylint")
 '(flycheck-stylelintrc "~/.stylelintrc.json")
 '(flyspell-abbrev-p t)
 '(flyspell-correct-interface (quote flyspell-correct-ivy) t)
 '(flyspell-issue-message-flag nil)
 '(flyspell-issue-welcome-flag nil)
 '(flyspell-mode 1 t)
 '(git-commit-summary-max-length 50)
 '(history-delete-duplicates t)
 '(history-length t)
 '(ispell-silently-savep t)
 '(ivy-count-format "(%d/%d) ")
 '(ivy-use-virtual-buffers t)
 '(ivy-virtual-abbreviate (quote full))
 '(org-agenda-dim-blocked-tasks t)
 '(org-agenda-files (quote ("~/.personal/agenda")))
 '(org-agenda-inhibit-startup t)
 '(org-agenda-show-log t t)
 '(org-agenda-skip-deadline-if-done t)
 '(org-agenda-skip-deadline-prewarning-if-scheduled (quote pre-scheduled))
 '(org-agenda-skip-scheduled-if-done t)
 '(org-agenda-span 2)
 '(org-agenda-start-on-weekday 6)
 '(org-agenda-sticky nil)
 '(org-agenda-tags-column -100)
 '(org-agenda-time-grid (quote ((daily today require-timed))))
 '(org-agenda-use-tag-inheritance t)
 '(org-archive-location "~/.personal/archives/%s::")
 '(org-blank-before-new-entry (quote ((heading . t) (plain-list-item . t))))
 '(org-columns-default-format "%14SCHEDULED %Effort{:} %1PRIORITY %TODO %50ITEM %TAGS")
 '(org-cycle-include-plain-lists (quote integrate))
 '(org-default-notes-file "~/.personal/agenda/organizer.org")
 '(org-directory "~/.personal")
 '(org-ditaa-jar-path "~/.local/lib/ditaa0_9.jar" t)
 '(org-enforce-todo-dependencies t)
 '(org-expiry-inactive-timestamps t t)
 '(org-export-backends
   (quote
    (ascii beamer html icalendar latex man md org texinfo)))
 '(org-habit-graph-column 80)
 '(org-habit-show-habits-only-for-today nil)
 '(org-log-done (quote time))
 '(org-log-into-drawer "LOGBOOK")
 '(org-modules
   (quote
    (org-crypt org-habit org-info org-irc org-mouse org-protocol)))
 '(org-refile-allow-creating-parent-nodes (quote confirm))
 '(org-refile-targets (quote ((org-agenda-files :maxlevel . 6))))
 '(org-refile-use-cache nil)
 '(org-refile-use-outline-path nil)
 '(org-startup-folded nil)
 '(org-startup-with-inline-images t)
 '(org-tag-alist
   (quote
    (("@coding" . 99)
     ("@computer" . 108)
     ("@errands" . 101)
     ("@home" . 104)
     ("@phone" . 112)
     ("@reading" . 114)
     ("@school" . 115)
     ("@work" . 98)
     ("@writing" . 119)
     ("crypt" . 67)
     ("fuzzy" . 48)
     ("highenergy" . 49))))
 '(org-tags-exclude-from-inheritance (quote ("crypt" "project")))
 '(org-todo-keywords
   (quote
    ((sequence "TODO(t)" "STARTED(s)" "WAITING(w@/!)" "SOMEDAY(.)" "|" "DONE(x!)" "CANCELLED(c@)")
     (sequence "TOBUY" "TOSHRINK" "TOCUT" "TOSEW" "|" "DONE(x)"))))
 '(org-track-ordered-property-with-tag t)
 '(org-use-effective-time t)
 '(org-use-speed-commands (quote my/org-use-speed-commands-for-headings-and-lists))
 '(org-yank-adjusted-subtrees t)
 '(package-selected-packages
   (quote
    (latex-preview-pane latex-preview-pane-mode yarn-mode yaml-mode vue-mode tide sql-indent plantuml-mode ac-php markdown-mode lua-mode json-mode company-tern tern xref-js2 js2-refactor js2-mode prettier-js gradle-mode company-emacs-eclim eclim dockerfile-mode csv-mode scss-mode emmet-mode company-anaconda anaconda-mode company-math company-auctex auctex yasnippet-snippets winum which-key webpaste web-mode use-package-ensure-system-package toc-org symon switch-window sudo-edit spacemacs-theme spaceline solarized-theme smex smartparens smart-mode-line react-snippets rainbow-mode rainbow-delimiters projectile pdf-tools org-plus-contrib org-bullets nord-theme nlinum neotree move-text magit lorem-ipsum ivy-yasnippet ivy-rich ivy-pass imgbb ido-vertical-mode hungry-delete git-timemachine git-gutter flyspell-correct-ivy flycheck exwm evil dracula-theme dmenu diminish delight dashboard counsel company color-theme-sanityinc-tomorrow beacon avy aggressive-indent)))
 '(pdf-view-display-size (quote fit-page))
 '(pdf-view-resize-factor 1.1)
 '(pdf-view-use-unicode-ligther nil)
 '(projectile-cache-file "/home/michael/.emacs.d/.projectile-cache")
 '(projectile-completion-system (quote ivy))
 '(projectile-enable-caching t)
 '(projectile-known-projects-file "/home/michael/.emacs.d/.projectile-bookmarks")
 '(projectile-mode-line (quote (:eval (projectile-project-name))) t)
 '(savehist-additional-variables (quote (kill-ring search-ring regexp-search-ring)))
 '(savehist-file "/home/michael/.emacs.d/history")
 '(savehist-save-minibuffer-history 1)
 '(set-mark-command-repeat-pop t)
 '(undo-tree-visualizer-diff t)
 '(undo-tree-visualizer-timestamps t)
 '(web-mode-attr-indent-offset 2 t)
 '(web-mode-block-padding 2 t)
 '(web-mode-code-indent-offset 2 t)
 '(web-mode-comment-style 2 t)
 '(web-mode-css-indent-offset 2 t)
 '(web-mode-enable-current-element-highlight t t)
 '(web-mode-markup-indent-offset 2 t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#000000" :foreground "#6A8397" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :foundry "GOOG" :family "Inconsolata")))))
